#!/usr/bin/env php

<?php
require __DIR__.'/../vendor/autoload.php';

use Nidup\Sandbox\ApiCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

$application = new Application('nidup-api-sandbox', '1.0.0');
$command = new ApiCommand();

$application->add($command);
$application->run();
